# Generated by Django 3.2.9 on 2022-01-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_camera_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
